# Generated by Django 5.2 on 2025-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('username', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=366, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='profile/business/')),
                ('tel', models.IntegerField()),
                ('location', models.CharField(max_length=366)),
                ('working_hours', models.CharField(max_length=366)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('username', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=366, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='profile/customer/')),
            ],
        ),
    ]
