# Generated by Django 5.2.1 on 2025-05-14 20:10

from django.db import migrations, models

def copy_uploaded_to_created(apps, schema_editor):
    MyModel = apps.get_model('auth_app', 'customerprofile')
    for obj in MyModel.objects.all():
        obj.created_at = obj.uploaded_at
        obj.save(update_fields=['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_businessprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
