# Generated by Django 5.2.1 on 2025-05-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customerprofile_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
