# Generated by Django 5.2.1 on 2025-05-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['first_name']},
        ),
    ]
