# Generated by Django 5.2 on 2025-04-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=366)),
                ('text', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='single_offer/')),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='auth_app.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OfferOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=366)),
                ('price', models.FloatField()),
                ('offer_type', models.CharField(choices=[('base', 'Base'), ('standard', 'Standard'), ('premium', 'Premium')], default='base')),
                ('delivery_time_in_days', models.CharField()),
                ('revisions', models.CharField(max_length=155)),
                ('list', models.TextField()),
                ('features', models.JSONField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerOption', to='coderr_app.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='in_progress')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth_app.businessprofile')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth_app.customerprofile')),
                ('offer_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coderr_app.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth_app.businessprofile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coderr_app.offer')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth_app.customerprofile')),
            ],
        ),
    ]
