# Generated by Django 5.2.1 on 2025-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_alter_offer_updated_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
